### ISSUE TITLE
python errors

### ISSUE THREAD

**Issue by AlisterH** [pedrocamargo/getthemfiltered#1]
Hi, just having this plugin enabled causes python errors, particularly when removing layers:
````
2019-11-22T14:32:36     WARNING    Traceback (most recent call last):
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\empty/python/plugins\getthemfiltered\get_them_filtered_dialog.py", line 64, in add_fields_to_cboxes
              self.reset_filter()
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\empty/python/plugins\getthemfiltered\get_them_filtered_dialog.py", line 80, in reset_filter
              self.layer.setSubsetString("")
             RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
````
I also often get the same errors when I try to use it, and often when adding layers, but perhaps in that case they only occur because I have already had an error from removing a layer - I am not sure.
I have tested in a clean profile, so I don't think it can be anything particularly special about my setup.  Perhaps the plugin only works in QGIS master?

Here is another error I get if I check the zoom button:
````
2019-11-22T14:44:14     WARNING    Traceback (most recent call last):
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\empty/python/plugins\getthemfiltered\get_them_filtered_dialog.py", line 102, in do_zooming
              self.iface.setActiveLayer(self.layer)
             RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted
````

**Comment by pedrocamargo** [comment]
I have never tested with developing versions of QGIS, but will investigate.

**Comment by AlisterH** [comment]
Yes, I think that fixed it all.

**Comment by pedrocamargo** [comment]
I have submitted the new version. It should be available in the repository soon.
