### ISSUE TITLE
When the plugin is enabled it causes errors adding and removing raster layers

### ISSUE THREAD

**Issue by AlisterH** [pedrocamargo/getthemfiltered#3]
Hi, the latest version causes errors when raster layers are added or removed:
````
2020-02-12T15:11:46     WARNING    Traceback (most recent call last):
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\getthemfiltered\get_them_filtered_dialog.py", line 79, in add_fields_to_cboxes
              self.changed_field()
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\getthemfiltered\get_them_filtered_dialog.py", line 85, in changed_field
              self.reset_filter()
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\getthemfiltered\get_them_filtered_dialog.py", line 91, in reset_filter
              self.layer.setSubsetString("")
             AttributeError: 'QgsRasterLayer' object has no attribute 'setSubsetString'
             
2020-02-12T15:12:03     WARNING    Traceback (most recent call last):
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\getthemfiltered\get_them_filtered_dialog.py", line 74, in add_fields_to_cboxes
              self.reset_filter()
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\getthemfiltered\get_them_filtered_dialog.py", line 91, in reset_filter
              self.layer.setSubsetString("")
             AttributeError: 'QgsRasterLayer' object has no attribute 'setSubsetString'
````
I guess it should be ignoring the raster layers, but a test is missing.  

I do also wonder why the plugin needs to do anything just because it is enabled.  Couldn't it wait until I open it and tell it to do some filtering?

**Comment by pedrocamargo** [comment]
The problem has been fixed and a new version has been uploaded to the plugin repository. It is currently pending approval.
